# gChat Configuration

# If a player doesn't have permission for any of the formats, should the chat message be passed through to the
# backend server or just ignored.
passthrough: true

# Logs chat to Velocity log
# Note: the log-chat and log-file options from gChat are not supported in gChat-Velocity
log-chat-global: true

# if permissions are required to send/receive chat messages
require-permission:
  # if true, players will need to have the "gchat.send" permission to send messages
  send: false

  # the message to send if a player doesn't have permission to chat
  # will only be sent if the 'passthrough' option below is false
  send-fail: "&cYou do not have permission to use the chat!"

  # if true, players will need to have the "gchat.receive" permission to receive messages
  receive: false

  # if a player doesn't have permission to send a message, should it be passed through to the backend server?
  passthrough: true

# Send data to an external service?
push-events:
  enabled: false
  endpoint: 'https://my.server.com'

# Tablist
tablist:
  header:
    - ''
    - '  &8▬▬▬▬▬▬▬▬&8▬▬▬▬▬▬▬▬&8▬▬▬▬▬▬▬▬&8▬▬▬▬▬▬▬▬[ &bMy Server Name &8]&8▬▬▬▬▬▬▬▬&8▬▬▬▬▬▬▬▬&8▬▬▬▬▬▬▬▬&8▬▬▬▬▬▬▬▬  '
    - ''
    - '&7Players online: &b{playercount}'
    - ''
  footer:
    - ''
    - '  &8▬▬▬▬▬▬▬&8▬▬▬▬▬▬▬▬&8▬▬▬▬▬▬▬▬&8▬▬▬▬▬▬▬▬[ &bServer info &8]&8▬▬▬▬▬▬▬▬&8▬▬▬▬▬▬▬▬&8▬▬▬▬▬▬▬▬&8▬▬▬▬▬▬▬  '
    - ''
    - '&7Connected to: &b{server_name}'
    - ''
    - '&7TPS: &b{tps} &8| &7MSPT: &b{mspt}'
    - '&7Date: &b{server_date} &8| &7Time: &b{server_time}'
    - ''
    - '&7NZ: &b{local_time_NZ} &8| &7EU: &b{local_time_CET} &8| &7NY: &b{local_time_EST} &8| &7LA: &b{local_time_PST}'
    - ''
    - '  &8▬▬▬▬▬▬▬▬&8▬▬▬▬▬▬▬▬&8▬▬▬▬▬▬▬▬&8▬▬▬▬▬▬▬▬&8▬▬▬▬▬▬▬▬&8▬▬▬▬▬▬▬▬&8▬▬▬▬▬▬▬▬&8▬▬▬▬▬▬▬▬&8▬▬▬▬▬▬▬▬&8▬▬▬▬▬▬▬▬▬  '
    - ''
    - '&7Your Ping: &b{ping}'
    - ''

# Defines the formats to be used.
formats:

  # A login format
  everyone-login:
    type: "login"
    check-permission: false
    format: "{luckperms_prefix}{name}{luckperms_suffix} &ehas logged on to the network"
    format-extra:

      # the format for the message tooltip
      hover: "AKA {display_name}"

      # what should happen when the message is clicked?
      click:

        # type: can be either "none", "suggest_command", "run_command" or "open_url"
        type: "none"

        # the value to suggest or run.
        value: ""

  # A server-join format
  everyone-join:
    type: "join"
    check-permission: false
    format: "{luckperms_prefix}{name}{luckperms_suffix} &ehas joined the {server} server"
    format-extra:

      # the format for the message tooltip
      hover: "Click to join {display_name} on the {server} server"

      # what should happen when the message is clicked?
      click:

        # type: can be either "none", "suggest_command", "run_command" or "open_url"
        type: "suggest_command"

        # the value to suggest or run.
        value: "/server {server}"

  # A logout format
  everyone-logout:
    type: "logout"
    check-permission: false
    format: "{luckperms_prefix}{name}{luckperms_suffix} &ehas logged out of the network"


  # a default format for everyone on the server
  everyone:

    # This is a chat-format
    type: "chat"

    # the priority of the format. higher number = higher priority.
    # if a user has permission for multiple formats, the one with the highest priority will be used.
    priority: 100

    # if this format requires a permission.
    # permissions are in the format: "gchat.format.<format name>"
    # for example: "gchat.format.everyone"
    check-permission: true

    # the actual format for the chat message
    format: "{luckperms_prefix}{name}{luckperms_suffix}{message}"

    format-extra:

      # the format for the message tooltip
      hover: ""

      # what should happen when the message is clicked?
      click:

        # type: can be either "none", "suggest_command", "run_command" or "open_url"
        type: "none"

        # the value to suggest or run.
        value: ""

  # another format without all the comments!
  staff:
    priority: 150
    check-permission: true
    format: "* {luckperms_prefix}{name}{luckperms_suffix}&c: &b&l{message}"
    format-extra:
      hover: |-
        &e{name} is a staff member!

        &6Feel free to message them any time, by
        &6clicking this message!
      click:
        type: suggest_command
        value: "/msg {name} "

# The style for links pasted in chat; you can use any JSON formatting, including hover events
link-style:
  underline: true
  hoverEvent:
    action: show_text
    value:
      text: "Click here to visit URL."
      color: aqua
